// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/mantenimiento": {
    params: {};
  };
  "/documentacion": {
    params: {};
  };
  "/estudiantes": {
    params: {};
  };
  "/reportes": {
    params: {};
  };
  "/boveda": {
    params: {};
  };
  "/perfil": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/mantenimiento" | "/documentacion" | "/estudiantes" | "/reportes" | "/boveda" | "/perfil" | "/login" | "/*";
  };
  "routes/[mantenimiento]._index.jsx": {
    id: "routes/[mantenimiento]._index";
    page: "/mantenimiento";
  };
  "routes/[documentacion]._index.jsx": {
    id: "routes/[documentacion]._index";
    page: "/documentacion";
  };
  "routes/[estudiantes]._index.jsx": {
    id: "routes/[estudiantes]._index";
    page: "/estudiantes";
  };
  "routes/[reportes]._index.jsx": {
    id: "routes/[reportes]._index";
    page: "/reportes";
  };
  "routes/[boveda]._index.jsx": {
    id: "routes/[boveda]._index";
    page: "/boveda";
  };
  "routes/[perfil]._index.jsx": {
    id: "routes/[perfil]._index";
    page: "/perfil";
  };
  "routes/[login]._index.jsx": {
    id: "routes/[login]._index";
    page: "/login";
  };
  "routes/_index.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/[404]._index.jsx": {
    id: "routes/[404]._index";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/[mantenimiento]._index": typeof import("./app/routes/[mantenimiento]._index.jsx");
  "routes/[documentacion]._index": typeof import("./app/routes/[documentacion]._index.jsx");
  "routes/[estudiantes]._index": typeof import("./app/routes/[estudiantes]._index.jsx");
  "routes/[reportes]._index": typeof import("./app/routes/[reportes]._index.jsx");
  "routes/[boveda]._index": typeof import("./app/routes/[boveda]._index.jsx");
  "routes/[perfil]._index": typeof import("./app/routes/[perfil]._index.jsx");
  "routes/[login]._index": typeof import("./app/routes/[login]._index.jsx");
  "routes/_index": typeof import("./app/routes/_index.jsx");
  "routes/[404]._index": typeof import("./app/routes/[404]._index.jsx");
};